/**
 * Dumps BUNDLE_CARDS to `supabase/seed/0002_seed_cards.sql`.
 *
 * Run with: `npm run seed:generate`
 *
 * The generated file is idempotent — it uses ON CONFLICT DO UPDATE so
 * you can re-run it after editing local seed content. Paste the file
 * contents into Supabase Dashboard → SQL Editor → Run.
 *
 * NEVER include the service_role key here; this script is local only.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { BUNDLE_CARDS } from '../src/data/bundle';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const OUT = resolve(__dirname, '../supabase/seed/0002_seed_cards.sql');

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlJsonb(value: unknown): string {
  // Postgres JSONB literal — JSON encode then escape single quotes.
  const json = JSON.stringify(value);
  return `${sqlString(json)}::jsonb`;
}

const rows = BUNDLE_CARDS.map((card) => {
  return `(${[
    sqlString(card.id),
    sqlString(card.type),
    sqlString(card.slug),
    sqlString(card.locale),
    sqlString(card.status),
    sqlJsonb(card),
  ].join(', ')})`;
});

const sql = `-- Auto-generated by scripts/generate-seed-sql.ts
-- Source: src/data/cards/*.ts (BUNDLE_CARDS at build time)
-- Idempotent — safe to re-run after content edits.

insert into public.cards (id, type, slug, locale, status, data)
values
${rows.join(',\n')}
on conflict (id) do update set
  type = excluded.type,
  slug = excluded.slug,
  locale = excluded.locale,
  status = excluded.status,
  data = excluded.data,
  updated_at = now();
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, sql, 'utf8');

// eslint-disable-next-line no-console
console.log(`✓ wrote ${BUNDLE_CARDS.length} cards → ${OUT}`);
